import type { Metadata } from 'next';
import './globals.scss';
import { Rubik } from 'next/font/google';
import { Suspense } from 'react';
import Loading from './loading';

const rubik = Rubik({
	subsets: ['latin'],
	weight: 'variable',
	variable: '--font-rubik',
});

export const metadata: Metadata = {
	title: 'TrackIt',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<Suspense fallback={<Loading />}>
				<body className={`${rubik.className} antialiased`}>{children}</body>
			</Suspense>
		</html>
	);
}
