import type { Metadata } from 'next';
import './globals.scss';
import Link from 'next/link';
import styles from './Home.module.scss';
import { Rubik } from 'next/font/google';

const rubik = Rubik({
	subsets: ['latin'],
	weight: 'variable',
	variable: '--font-rubik',
});

export const metadata: Metadata = {
	title: 'Next Tasks',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${rubik.variable} antialiased`}>
				<header>
					<nav className={styles.nav}>
						<Link href={'/'}>
							<span>Home</span>
						</Link>
						<Link href={'tasks'}>
							<span>Tasks</span>
						</Link>
					</nav>
				</header>
				{children}
			</body>
		</html>
	);
}
